### ISSUE TITLE
Windows build fails: 86 tests completed, 2 failed

### ISSUE THREAD

**Issue by alidehkhodaei** [iluwatar/30-seconds-of-java#152]
Hello, I running ./gradlew clean build but 2 test faild. May it occure only on my system?
More detail:

86 tests completed, 2 failed

1. ListFilesInDirectorySnippetTest > testListFilesInDirectory() FAILED
    org.opentest4j.AssertionFailedError at ListFilesInDirectorySnippetTest.java:48

2. InputStreamToStringSnippetTest > testInputStreamToString() FAILED
    org.opentest4j.AssertionFailedError at InputStreamToStringSnippetTest.java:52

**Comment by iluwatar** [comment]
CI build for `master` is succeeding. Also works on my machine. 🤷🏻‍♂️

**Comment by alidehkhodaei** [comment]
It faild on my machine.
I guess it may occure on different os because two faild test are about file and io.🤷🏻‍♂️🤔

**Comment by iluwatar** [comment]
Which OS are you on?

**Comment by iluwatar** [comment]
Ok, that may be the reason. The CI build is running on Ubuntu Linux and I'm on Mac.

**Comment by Bhaskar1312** [comment]
The `testInputStreamToString()` test is failing due to line-separator difference in windows
`@Test
  void testInputStreamToString() throws IOException {
    String str = "ąćśź\r\n"
            + "←≠²³¢²€\r\n"
            + "июля\r\n"
            + "åøä\r\n"
            + "ñí\r\n"
            + "7月15日起\r\n"
            + "خەيرلىك ئەتىگەن!";
    assertEquals(str, InputStreamToStringSnippet.inputStreamToString(
            new FileInputStream("src\\test\\resources\\dir1\\placeholder.txt")));
    assertNotEquals(str.toUpperCase(), InputStreamToStringSnippet.inputStreamToString(
            new FileInputStream("src\\test\\resources\\dir1\\placeholder.txt")));
  }`
  The following test passes if the line separator of `src/test/resources/dir1/placeholder.txt` is CRLF(\r\n) and changing '/' to '\\'
  or original test passes if we change the line separator of `src/test/resources/dir1/placeholder.txt` to LF without changing line-separator in unit test string.
  
  For the other test
  ` @Test
  void testListFilesInDirectory() {
    var files = ListFilesInDirectorySnippet.listFilesInDirectory(new File("src/test/resources"));
    assertEquals(2, files.length);
    var filenames = new HashSet<>(Arrays.asList(files[0].toString(), files[1].toString()));
    assertTrue(filenames.contains("src\\test\\resources\\somelines.txt"));
    assertTrue(filenames.contains("src\\test\\resources\\someotherlines.txt"));
  }`
  The above test passes(changed the separator from '/' to '\\'

**Comment by Bhaskar1312** [comment]
https://github.com/iluwatar/30-seconds-of-java/pull/162
